server:
  port: 8082
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/senac
    password: gabi1234
    username: postgres
    driverClassName: org.postgresql.Driver

